version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - 8000:8080
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.66.166.165:5432/db_sac_prusso
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update